Repository AkijVenture/akij-turborepo, pull requests merged in 2023-01, with the labels that each got.

#86 feat: created Partner, PartnerImages, Partner.mocks, Partner.stories …
  apps/akij-food-beverage/src/components/ui/features/PartnerSection/Partner.mocks.tsx
  apps/akij-food-beverage/src/components/ui/features/PartnerSection/Partner.stories.tsx
  apps/akij-food-beverage/src/components/ui/features/PartnerSection/Partner.tsx
  apps/akij-food-beverage/src/components/ui/features/PartnerSection/PartnerImages.tsx
  apps/akij-food-beverage/src/pages/index.tsx
Labels: Design, Feature, Front-end, Test, STORYBOOK

#87 feat: 📦: Issue #79 Banner component added in features
  apps/akij-food-beverage/src/components/ui/elements/buttons/Button.tsx
  apps/akij-food-beverage/src/components/ui/elements/buttons/Buttons.stories.tsx
  apps/akij-food-beverage/src/components/ui/features/Banner/Banner.stories.tsx
  apps/akij-food-beverage/src/components/ui/features/Banner/Banner.tsx
  apps/akij-food-beverage/src/components/ui/features/Banner/content/Content.tsx
  apps/akij-food-beverage/src/components/ui/features/Banner/content/ProductImage.tsx
  apps/akij-food-beverage/src/components/ui/features/Banner/index.ts
  apps/akij-food-beverage/src/pages/index.tsx
  apps/akij-food-beverage/src/styles/globals.css
Labels: Feature, Front-end, Test, STORYBOOK

#88 feat(features/introductionsection): 81 add introduction section in fe…
  apps/akij-food-beverage/src/components/ui/features/IntroductionSection/Introduction.stories.tsx
  apps/akij-food-beverage/src/components/ui/features/IntroductionSection/Introduction.tsx
  apps/akij-food-beverage/src/components/ui/features/IntroductionSection/index.ts
  apps/akij-food-beverage/src/pages/index.tsx
  apps/akij-food-beverage/src/styles/globals.css
  apps/akij-food-beverage/src/utils/useFetch.ts
  packages/ui/components/elements/Icon/arrow.tsx
  packages/ui/components/elements/Icon/checkmark.tsx
Labels: enhancement, Feature, Front-end, STORYBOOK
